# Generated by Django 4.0.6 on 2022-08-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_student_city_remove_student_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Email',
        ),
    ]
